# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  - osx
julia:
  - release
  - nightly
notifications:
  email: false
# uncomment the following lines to override the default test script
script:
 - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
 - export DEPS_DIR=${HOME}/deps
 - mkdir ${DEPS_DIR}
 - cd ${DEPS_DIR}
 - if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
 -   CMAKE_URL="http://www.cmake.org/files/v3.7/cmake-3.7.1-Linux-x86_64.tar.gz"
 -   mkdir cmake && wget --quiet -O - ${CMAKE_URL} | tar --strip-components=1 -xz -C cmake
 -   export PATH=${DEPS_DIR}/cmake/bin:${PATH}
 - else
 - brew upgrade cmake || brew install cmake
 - fi
 - cmake --version
 - julia -e 'Pkg.clone(pwd()); Pkg.build("OSQP"); Pkg.test("OSQP"; coverage=true)'
after_success:
  # # push coverage results to Coveralls
  # - julia -e 'cd(Pkg.dir("OSQP")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
  # push coverage results to Codecov
  - julia -e 'cd(Pkg.dir("OSQP")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
