name = "OSQP"
uuid = "ab2f91bb-94b4-55e3-9ba0-7f65df51de79"
keywords = ["optimization", "solver", "numerical-optimization"]
license = "ASL"
desc = " Julia wrapper for OSQP: the Operator Splitting QP Solver."
repo = "https://github.com/oxfordcontrol/OSQP.jl.git"

[deps]
BinDeps = "9e28174c-4ba2-5203-b857-d8d62c4213ee"
Compat = "34da2185-b29b-5c13-b0c7-acf172513d20"
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"
MathOptInterface = "b8f27783-ece8-5eb3-8dc8-9495eed66fee"
MathProgBase = "fdba3010-5040-5b88-9595-932c9decdf73"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[targets]
test = ["Test", "Random"]
